name: hackathon_app_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.2.0
  intl: ^0.19.0
  flutter_contacts: ^1.1.7
  flutter_notification_listener: ^1.3.3
  http: ^1.2.1
  file_picker: ^6.1.1
  record_mp3: ^3.0.0
  path_provider: ^2.1.2
  installed_apps: ^1.5.0
  flutter_launcher_icons: ^0.13.1
  just_audio: ^0.9.36

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/persona-app.png"
  min_sdk_android: 21